import { jsPDF } from "jspdf";
import { Ebook } from "@/hooks/useEbookStore";

interface PDFSection {
  type: "h1" | "h2" | "h3" | "paragraph" | "bullet";
  content: string;
}

function parseContent(content: string | undefined): PDFSection[] {
  const safeContent = content || "";
  const sections: PDFSection[] = [];
  const lines = safeContent.split("\n");

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;

    if (trimmed.startsWith("### ")) {
      sections.push({ type: "h3", content: trimmed.replace("### ", "") });
    } else if (trimmed.startsWith("## ")) {
      sections.push({ type: "h2", content: trimmed.replace("## ", "") });
    } else if (trimmed.startsWith("# ")) {
      sections.push({ type: "h1", content: trimmed.replace("# ", "") });
    } else if (trimmed.startsWith("- ") || trimmed.startsWith("* ")) {
      sections.push({ type: "bullet", content: trimmed.substring(2) });
    } else if (/^\d+\.\s/.test(trimmed)) {
      sections.push({ type: "bullet", content: trimmed });
    } else if (trimmed === "---" || trimmed === "***") {
      continue;
    } else {
      sections.push({ type: "paragraph", content: trimmed });
    }
  }
  return sections;
}

function extractChapters(sections: PDFSection[]): string[] {
  return sections.filter((s) => s.type === "h2").map((s) => s.content);
}

export async function generatePDF(ebook: Ebook): Promise<void> {
  try {
    console.log("🚀 Starting PDF generation for:", ebook.title);

    const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

    const pw = doc.internal.pageSize.getWidth();
    const ph = doc.internal.pageSize.getHeight();
    const margin = 25;
    const cw = pw - margin * 2;
    const bodyLineH = 6.5;

    const colors = {
      primary: [55, 48, 163] as [number, number, number],
      text: [28, 28, 28] as [number, number, number],
      muted: [110, 110, 110] as [number, number, number],
      accent: [79, 70, 229] as [number, number, number],
      white: [255, 255, 255] as [number, number, number],
    };

    let pageNum = 0;
    let y = margin;

    const addPage = () => {
      doc.addPage();
      pageNum++;
      y = margin;
    };

    const footer = () => {
      doc.setFontSize(9);
      doc.setTextColor(...colors.muted);
      doc.text(`${pageNum}`, pw / 2, ph - 10, { align: "center" });
    };

    // FIX: after needsBreak triggers a new page, reset font/color
    // to avoid inheriting footer's muted/small style on first line
    const needsBreak = (space: number, resetFontSize?: number, resetColor?: [number, number, number]) => {
      if (y + space > ph - 20) {
        footer();
        addPage();
        // Reset styles after page break so text never inherits footer styling
        if (resetFontSize) doc.setFontSize(resetFontSize);
        if (resetColor) doc.setTextColor(...resetColor);
        return true;
      }
      return false;
    };

    const safeTitle = ebook.title || "Untitled Ebook";
    const safeTopic = ebook.topic || "";
    const safeContent = ebook.content || "";
    const safeCreatedAt = ebook.createdAt ? new Date(ebook.createdAt) : new Date();

    // ===== COVER =====
    pageNum++;
    doc.setFillColor(...colors.primary);
    doc.rect(0, 0, pw, ph, "F");

    doc.setTextColor(...colors.white);
    doc.setFontSize(36);
    const coverTitle = doc.splitTextToSize(safeTitle, cw - 20);
    const titleStartY = ph / 2 - coverTitle.length * 14;
    doc.text(coverTitle, pw / 2, titleStartY, { align: "center" });

    if (safeTopic) {
      doc.setFontSize(16);
      const topicLines = doc.splitTextToSize(safeTopic, cw - 40);
      doc.text(topicLines, pw / 2, titleStartY + coverTitle.length * 14 + 10, { align: "center" });
    }

    // doc.setFontSize(12);
    // doc.text("NexoraOS", pw / 2, ph - 25, { align: "center" });

    // ===== TITLE PAGE =====
    addPage();
    y = 55;
    doc.setTextColor(...colors.primary);
    doc.setFontSize(28);
    const tpTitle = doc.splitTextToSize(safeTitle, cw);
    doc.text(tpTitle, pw / 2, y, { align: "center" });
    y += tpTitle.length * 12 + 15;

    doc.setFontSize(13);
    doc.setTextColor(...colors.muted);
    doc.text(`Topic: ${safeTopic}`, pw / 2, y, { align: "center" });
    y += 12;
    // doc.text("Generated by NexoraOS", pw / 2, y, { align: "center" });
    y += 10;
    const dateStr = safeCreatedAt.toLocaleDateString("en-US", {
      year: "numeric", month: "long", day: "numeric",
    });
    doc.text(dateStr, pw / 2, y, { align: "center" });
    footer();

    // ===== TABLE OF CONTENTS =====
    const sections = parseContent(safeContent);
    const chapters = extractChapters(sections);

    if (chapters.length > 0) {
      addPage();
      y = margin;
      doc.setTextColor(...colors.primary);
      doc.setFontSize(24);
      doc.text("Table of Contents", margin, y);
      y += 18;

      doc.setDrawColor(...colors.accent);
      doc.setLineWidth(0.8);
      doc.line(margin, y, margin + 40, y);
      y += 12;

      doc.setFontSize(12);
      (chapters || []).forEach((chapter, i) => {
        needsBreak(10, 12, colors.text);
        doc.setFontSize(12);
        doc.setTextColor(...colors.text);
        const tocLine = doc.splitTextToSize(`${i + 1}.  ${chapter}`, cw - 10);
        doc.text(tocLine, margin + 5, y);
        y += tocLine.length * 6 + 5;
      });
      footer();
    }

    // ===== CONTENT =====
    addPage();

    (sections || []).forEach((section) => {
      switch (section.type) {
        case "h1": {
          if (y > margin + 10) {
            footer();
            addPage();
          }
          y += 5;
          doc.setFontSize(22);
          doc.setTextColor(...colors.primary);
          const h1 = doc.splitTextToSize(section.content, cw);
          doc.text(h1, margin, y);
          y += h1.length * 10 + 5;
          doc.setDrawColor(...colors.accent);
          doc.setLineWidth(0.6);
          doc.line(margin, y, margin + 30, y);
          y += 8;
          break;
        }
        case "h2": {
          needsBreak(22, 16, colors.accent);
          y += 6;
          doc.setFontSize(16);
          doc.setTextColor(...colors.accent);
          const h2 = doc.splitTextToSize(section.content, cw);
          doc.text(h2, margin, y);
          y += h2.length * 7 + 5;
          break;
        }
        case "h3": {
          needsBreak(18, 13, [70, 70, 70]);
          y += 4;
          doc.setFontSize(13);
          doc.setTextColor(70, 70, 70);
          const h3 = doc.splitTextToSize(section.content, cw);
          doc.text(h3, margin, y);
          y += h3.length * 6 + 4;
          break;
        }
        case "bullet": {
          needsBreak(bodyLineH + 2, 11, colors.text);
          doc.setFontSize(11);
          doc.setTextColor(...colors.text);
          const bulletLines = doc.splitTextToSize(section.content, cw - 8);
          doc.setFillColor(...colors.accent);
          doc.circle(margin + 2, y - 1.2, 1, "F");
          (bulletLines || []).forEach((line: string) => {
            needsBreak(bodyLineH, 11, colors.text);
            // FIX: always reset font and color before writing each line
            doc.setFontSize(11);
            doc.setTextColor(...colors.text);
            doc.text(line, margin + 7, y);
            y += bodyLineH;
          });
          y += 1;
          break;
        }
        case "paragraph": {
          doc.setFontSize(11);
          doc.setTextColor(...colors.text);
          const para = doc.splitTextToSize(section.content, cw);
          (para || []).forEach((line: string) => {
            needsBreak(bodyLineH, 11, colors.text);
            // FIX: always reset font and color before writing each line
            doc.setFontSize(11);
            doc.setTextColor(...colors.text);
            doc.text(line, margin, y);
            y += bodyLineH;
          });
          y += 3;
          break;
        }
      }
    });

    footer();

    // ===== INSTANT DOWNLOAD =====
    const filename = safeTitle
      .replace(/[^a-zA-Z0-9\s]/g, "")
      .replace(/\s+/g, "_")
      .substring(0, 60);

    const pdfBlob = doc.output("blob");
    const blobUrl = URL.createObjectURL(pdfBlob);

    const link = document.createElement("a");
    link.href = blobUrl;
    link.download = `${filename}.pdf`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(blobUrl);

    console.log(`✅ PDF downloaded: ${filename}.pdf`);

  } catch (error: any) {
    console.error("❌ PDF generation failed:", error);
    alert(`Download failed: ${error.message || error}`);
  }
}

export async function downloadCoverImage(ebook: Ebook): Promise<void> {
  if (!ebook.coverImageUrl) return;
  try {
    const response = await fetch(ebook.coverImageUrl);
    const blob = await response.blob();
    const blobUrl = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = blobUrl;
    const filename = (ebook.title || "cover")
      .replace(/[^a-zA-Z0-9\s]/g, "")
      .replace(/\s+/g, "_");
    link.download = `${filename}_cover.webp`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(blobUrl);
  } catch (error) {
    console.error("Error downloading cover image:", error);
    window.open(ebook.coverImageUrl, "_blank");
  }
  }
