import { jsPDF } from "jspdf";
import { Ebook } from "@/hooks/useEbookStore";

interface PDFSection {
  type: "h1" | "h2" | "h3" | "paragraph";
  content: string;
}

function parseContent(content: string): PDFSection[] {
  const sections: PDFSection[] = [];
  const lines = content.split("\n");

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;

    if (trimmed.startsWith("### ")) {
      sections.push({ type: "h3", content: trimmed.replace("### ", "") });
    } else if (trimmed.startsWith("## ")) {
      sections.push({ type: "h2", content: trimmed.replace("## ", "") });
    } else if (trimmed.startsWith("# ")) {
      sections.push({ type: "h1", content: trimmed.replace("# ", "") });
    } else {
      sections.push({ type: "paragraph", content: trimmed });
    }
  }

  return sections;
}

function extractChapters(sections: PDFSection[]): { title: string; index: number }[] {
  const chapters: { title: string; index: number }[] = [];
  sections.forEach((section, index) => {
    if (section.type === "h1" || section.type === "h2") {
      chapters.push({ title: section.content, index });
    }
  });
  return chapters;
}

export function generatePDF(ebook: Ebook): void {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 25;
  const contentWidth = pageWidth - margin * 2;
  const lineHeight = 7;
  const headerColor: [number, number, number] = [79, 70, 229]; // Indigo
  const textColor: [number, number, number] = [30, 30, 30];
  const mutedColor: [number, number, number] = [100, 100, 100];

  let currentPage = 1;
  let y = margin;

  // Helper: Add page number
  const addPageNumber = () => {
    doc.setFontSize(10);
    doc.setTextColor(...mutedColor);
    doc.text(String(currentPage), pageWidth / 2, pageHeight - 12, { align: "center" });
  };

  // Helper: Check page break
  const checkPageBreak = (requiredSpace: number = 20): void => {
    if (y + requiredSpace > pageHeight - margin - 15) {
      addPageNumber();
      doc.addPage();
      currentPage++;
      y = margin;
    }
  };

  // ===== PAGE 1: Cover Page =====
  if (ebook.coverImageUrl) {
    try {
      // Add cover image to fill the entire first page
      doc.addImage(ebook.coverImageUrl, "PNG", 0, 0, pageWidth, pageHeight);
    } catch {
      // Fallback: Create a styled cover
      doc.setFillColor(79, 70, 229);
      doc.rect(0, 0, pageWidth, pageHeight, "F");
      
      // Add gradient overlay
      doc.setFillColor(124, 58, 237);
      doc.rect(0, pageHeight * 0.6, pageWidth, pageHeight * 0.4, "F");
      
      // Title
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(32);
      const titleLines = doc.splitTextToSize(ebook.title, contentWidth - 20);
      const titleY = pageHeight / 2 - (titleLines.length * 12);
      doc.text(titleLines, pageWidth / 2, titleY, { align: "center" });
      
      // NexoraOS branding
      doc.setFontSize(14);
      doc.text("NexoraOS", pageWidth / 2, pageHeight - 30, { align: "center" });
    }
  } else {
    // No cover image - create styled cover
    doc.setFillColor(79, 70, 229);
    doc.rect(0, 0, pageWidth, pageHeight, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(32);
    const titleLines = doc.splitTextToSize(ebook.title, contentWidth - 20);
    doc.text(titleLines, pageWidth / 2, pageHeight / 2, { align: "center" });
    doc.setFontSize(14);
    doc.text("NexoraOS", pageWidth / 2, pageHeight - 30, { align: "center" });
  }

  // ===== PAGE 2: Title Page =====
  doc.addPage();
  currentPage++;
  
  doc.setTextColor(...headerColor);
  doc.setFontSize(28);
  const titleLines = doc.splitTextToSize(ebook.title, contentWidth);
  y = 60;
  doc.text(titleLines, pageWidth / 2, y, { align: "center" });
  
  y += titleLines.length * 12 + 20;
  
  doc.setFontSize(14);
  doc.setTextColor(...mutedColor);
  doc.text(`Topic: ${ebook.topic}`, pageWidth / 2, y, { align: "center" });
  
  y += 15;
  doc.text(`Generated by NexoraOS`, pageWidth / 2, y, { align: "center" });
  
  y += 10;
  const date = new Date(ebook.createdAt).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  doc.text(date, pageWidth / 2, y, { align: "center" });
  
  addPageNumber();

  // ===== PAGE 3: Table of Contents =====
  doc.addPage();
  currentPage++;
  y = margin;

  doc.setTextColor(...headerColor);
  doc.setFontSize(24);
  doc.text("Table of Contents", margin, y);
  y += 20;

  const sections = parseContent(ebook.content);
  const chapters = extractChapters(sections);

  doc.setFontSize(12);
  doc.setTextColor(...textColor);

  chapters.forEach((chapter, index) => {
    checkPageBreak(10);
    const prefix = chapter.title.toLowerCase().includes("introduction") || 
                   chapter.title.toLowerCase().includes("conclusion") 
      ? "" 
      : `${index + 1}. `;
    
    const tocText = `${prefix}${chapter.title}`;
    const lines = doc.splitTextToSize(tocText, contentWidth - 20);
    doc.text(lines, margin + 5, y);
    y += lines.length * 6 + 4;
  });

  addPageNumber();

  // ===== CONTENT PAGES =====
  doc.addPage();
  currentPage++;
  y = margin;

  sections.forEach((section) => {
    switch (section.type) {
      case "h1":
        checkPageBreak(30);
        y += 10;
        doc.setFontSize(22);
        doc.setTextColor(...headerColor);
        const h1Lines = doc.splitTextToSize(section.content, contentWidth);
        doc.text(h1Lines, margin, y);
        y += h1Lines.length * 10 + 8;
        break;

      case "h2":
        checkPageBreak(25);
        y += 8;
        doc.setFontSize(18);
        doc.setTextColor(...headerColor);
        const h2Lines = doc.splitTextToSize(section.content, contentWidth);
        doc.text(h2Lines, margin, y);
        y += h2Lines.length * 8 + 6;
        break;

      case "h3":
        checkPageBreak(20);
        y += 5;
        doc.setFontSize(14);
        doc.setTextColor(60, 60, 60);
        const h3Lines = doc.splitTextToSize(section.content, contentWidth);
        doc.text(h3Lines, margin, y);
        y += h3Lines.length * 6 + 4;
        break;

      case "paragraph":
        doc.setFontSize(11);
        doc.setTextColor(...textColor);
        const paraLines = doc.splitTextToSize(section.content, contentWidth);
        
        paraLines.forEach((line: string) => {
          checkPageBreak(lineHeight);
          doc.text(line, margin, y);
          y += lineHeight;
        });
        y += 3;
        break;
    }
  });

  // Add final page number
  addPageNumber();

  // Save PDF
  const filename = ebook.title.replace(/[^a-zA-Z0-9\s]/g, "").replace(/\s+/g, "_");
  doc.save(`${filename}.pdf`);
}

export function downloadCoverImage(ebook: Ebook): void {
  if (!ebook.coverImageUrl) return;

  const link = document.createElement("a");
  link.href = ebook.coverImageUrl;
  const filename = ebook.title.replace(/[^a-zA-Z0-9\s]/g, "").replace(/\s+/g, "_");
  link.download = `${filename}_cover.png`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}
