project_id = "uxojubleolviktarveyy"

[functions.generate-ebook-title]
verify_jwt = false

[functions.generate-ebook-content]
verify_jwt = false

[functions.generate-ebook-cover]
verify_jwt = false

[functions.whop-webhook]
verify_jwt = false

[functions.product-tracking]
verify_jwt = false

[functions.monetization]
verify_jwt = false

[functions.generate-marketing]
verify_jwt = false

[functions.analytics-connect]
verify_jwt = false

[functions.analytics-fetch]
verify_jwt = false

[functions.analytics-chat]
verify_jwt = false
[functions.find-winning-niches]
verify_jwt = false
